### PR TITLE
Fix for Bug #42. 

### LINKED ISSUE #42: !dkp responses are indeterminate when using multiple teams
**Describe the bug**
Using 3.0 r7: If user A whispers !dkp to user B, user B replies with a dkp value of whichever team user B last viewed. From User A's point of view, the reply is unpredictable.

**To Reproduce**

User A - regular raider. User B - officer. User C - officer.
1. User A wants to see team 1 DKP.
2. User B (officer) views Team 2, and closes CommunityDKP
3. User C (officer) views Team 1 and closes CommunityDKP
4 User A whispers User B. User B replies with team2 dkp as that's the last team he was viewing. User A, though, doesn't know which team the reply applies to. it appears to be random.
5. Since they're confused, user A whispers user C and receives team1 dkp. User A is confused because the officers are reporting two different values, and User A doesn't know how to force a response of team 1 dkp.

**Expected behavior**
When commDKP replies on User B, it should reply with User A's dkp in every team. And the output line should include the team name so it's clear which line applies to which team.

Or allow user A to query by team, such as "!dkp myName Black Wing Lair

**Screenshots**

**CommunityDKP Version**
3.0 r7:

**Additional context**

### PR DESCRIPTION
**Pull request by Vapok**
Fix for #42 

This will display a new line for each team that the user is found in.
image

### CODE REVIEW

**Review by Taidtuskecyh — COMMENTED** [review]
Looks okay but since u are not using CommDKP:GetGuildTeamList() this might return team values out of order (string index)

**Comment by Vapok** [comment]
Ah!  let me use that!

**Comment by Vapok** [comment]
We might want to revisit that method in the future to just return the entire team object instead of just the name to future proof changes to that object.

**Comment by Taidtuskecyh** [comment]
the only problem with it atm would be if we started deleting teams so yeah. In the future this will be problematic

**Pull request merged**
